apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mycv.fullname" . }}
  labels:
    {{- include "mycv.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mycv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        github.action.build: "{{ .Values.githubActionRun }}"
      labels:
        {{- include "mycv.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mycv.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              value: "mongodb://mycv-mongodb:27017"
            {{ if .Values.jacoco.enabled }}
            - name: JAVA_OPTIONS
              value: {{ .Values.jacoco.javaOptions }}
            {{ end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            {{ if .Values.jacoco.enabled }}
            - name: jacoco
              containerPort: 6300
              protocol: TCP
            {{ end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
