apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycv.fullname" . }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    {{- include "mycv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "mycv.selectorLabels" . | nindent 4 }}
